# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"
defaultContentLanguage = "zh-Hans"

# SEO优化设置
title = "Arkin的博客 - 技术分享与思考"
description = "个人技术博客，分享AI应用、Web开发、数据科学等技术内容，记录学习心得和项目经验"
keywords = ["技术博客", "AI应用", "Web开发", "数据科学", "机器学习", "全栈开发"]
author = "Arkin"
languageCode = "zh-Hans"
defaultContentLanguageInSubdir = true

# URL和链接优化
canonifyURLs = true
relativeURLs = false
removePathAccents = true
uglyURLs = false

# 搜索引擎优化
enableRobotsTXT = true
enableGitInfo = true
summaryLength = 0

# 明确 front matter 的优先级，避免 Git 提交时间覆盖 lastmod
[frontmatter]
  lastmod = ["lastmod", "date", "publishDate", "expiryDate"]

# 输出格式
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

# 分页设置
[pagination]
  pagerSize = 15

# 隐私设置
[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

# 服务设置
[services]
  [services.x]
    disableInlineCSS = true

# 图片处理
[imaging]
  quality = 85
  resampleFilter = "Lanczos"
  anchor = "Smart"

# 压缩设置
[build]
  writeStats = true

# 模块设置
[module]
  [module.hugoVersion]
    extended = true
    min = "0.120.0"
