languageCode = "zh-Hans"
languageName = "简体中文"
languageDirection = "ltr"
weight = 1

title = "Arkin的博客"

[params]
  dateFormat = "2006年1月2日"

  mainSections = ["posts"]
  description = "这是一个使用Hugo和Congo主题构建的个人博客"

[params.author]
  name = "ArkinDev"
  image = "img/author.jpg"
  headline = "热爱技术的全栈开发者"
  bio = "专注于Web开发和开源项目，喜欢探索新技术，分享学习经验"
  links = [
    { email = "mailto:your.email@example.com" },
    { github = "https://github.com/yourusername" },
    { x-twitter = "https://twitter.com/yourusername" },
    { linkedin = "https://linkedin.com/in/your-profile" },
  ]
